### ISSUE TITLE
Create a release of halbuilder-jaxrs

### ISSUE THREAD

**Issue by kschulst** [HalBuilder/halbuilder-jaxrs#1]
Would it be possible to create a relase for this so that we can pull it from maven central?

**Comment by talios** [comment]
Yep!  Will do.  I kept meaning to flesh a bit more of it out ( tho I don't use JAX-RS so any contribs would be nice ).  But will cut a release of whats there currently.

**Comment by talios** [comment]
...and done.  Should be winging its way to central within the hour.

**Comment by kschulst** [comment]
Hehey :) Thanks a lot, and also thanks for the quick response!

Will look into how I can contribute!

Until now, the only issue I have found a bit cumbersome (and it is not related to halbuilder-jaxrs) is that I would like to use my own objectmapper instance - but preferrably without having to provide an entirely new implementation/override of the JsonRepresentation(Reader/Writer) classes.

**Comment by talios** [comment]
It'd be easy to add a `withObjectMapper` and/or `withJsonGenerator` on the constructor for `JsonRepresentationWriter` but I've long wanted to shield "jackson" from the public API ( i.e. if I decided to switch to Boon ( already thinking of ... ) ). Currently the fact that Jackson is used is pretty much an internal implementation detail.

Tho I'm thinking that if I did do such a change, I'd probably switch to using `JacksonJsonRepresentationWriter` and `BoonJsonRepresentationWriter` ( possibly in separate artifacts / repositories as well ).

**Comment by kschulst** [comment]
Sounds like a reasonable rename - which will make it very explicit which json provider is used underneath. And then providing these wither-methods for customization would also be cleaner after this refactoring. It would be great to be able to get support for e.g. guava data models in HALBuilder's object mapper.

Out of curiosity, what is your selling point rationale of switching to Boon? Performance?
I don't have any experience with Boon, but Jackson has vast amount of addons and I would argue it is the most common library of its kind. 

I also like the idea of separating out support for each of these providers in their own artifacts/modules.

Speaking about modules, have you looked into standardizing the version numbers/release cycle for all modules and provide a maven bom (Bill of Materials) in order to make it easier to keep track of versions?I found it a bit awkward that each "sub module" has its own version/release cycle.

Sorry for turning this thread into a chat room ;-)
