### ISSUE TITLE
Method `MessageBodyWriter#getSize` not implemented correctly.

### ISSUE THREAD

**Issue by g-fresh** [HalBuilder/halbuilder-jaxrs#6]
The method `JaxRsHalBuilderSupport#getSize` returns the number of characters rather than the number of bytes.
This leads to an error when the library is used with Jersey 1.x (the response is truncated if the entity contains any characters encoded with more than one byte).

I suppose halbuilder doesn't officially support Jersy 1.x.
However, in Jersey 2 the method `MessageBodyWriter#getSize` was deprecated.
The content length is determined by the framework.
I think `JaxRsHalBuilderSupport#getSize` should be a NO-OP in order to not have the conversion to JSON done twice.

**Comment by bodewig** [comment]
you are correct, see #7
