### ISSUE TITLE
Feature request: Allow lookup of ObjectMapper via ContextResolver

### ISSUE THREAD

**Issue by sventorben** [HalBuilder/halbuilder-jaxrs#8]
JAX-RS allows the lookup of ObjectMapper via ContextResolver. A good example for this is given in the [JacksonJsonProvider](https://github.com/FasterXML/jackson-jaxrs-json-provider/blob/master/src/main/java/com/fasterxml/jackson/jaxrs/json/JacksonJsonProvider.java).
Such a feature would enable customized (de)serialization with ease.

However, I guess this needs some modifications to HalBuilder/halbuilder-json as already discussed in HalBuilder/halbuilder-json#2. Need to implement a way to set the ObjectMapper in JsonRepresentationReader/Writer.

Would be happy to prepare and provide PR. However, I am not sure about the current status of this project - is this still actively maintained?

**Comment by talios** [comment]
halbuilder-jaxrs is as maintained as you want it to be really.  I don't use Jax-RS personally and this subproject started as a small example/experiment.

HalBuilder itself is still maintained, tho HalBuilder5 is an API breaking implementation.

I'll look at the PR tonight and merge/release if all good.

**Comment by sventorben** [comment]
Thanks, that's very much appreciated.

When preparing the release, please consider increasing the major or at least minor version. For some people the behavior may change if a ContextResolver<ObjectMapper> is registered. The ContextResolver will now be picked up automatically, so that (de)serialization results may be different, because halbuilder-jaxrs will be using the provided ObjectMapper.

**Comment by talios** [comment]
Resolved as part of the new `halbuilder-core-5.1.1` and `halbuilder-jaxrs-5.1.1` releases.
